### ISSUE TITLE
"included_fonts" folder not created on Linux(?)

### ISSUE THREAD

**Issue by RfzVd** [Toocanzs/AnkiJapaneseCardRandomizer#1]
The "included_fonts" folder wasn't created after installing the addon, instead "included_fonts\\" was prefixed to the filenames of the font files, i.e. "included_fonts\\_chigfont.ttf" was the filename of that font for example. Here's a picture: https://i.imgur.com/IV4Mtqv.png.

After creating the folder, copying the fonts to it and renaming them they seemed to work normally and were copied to the media folder.

I installed with the normal anki addon manager using the addon code.

(Thank you for the addon!)

**Comment by Toocanzs** [comment]
Actually jumped the gun on that one (although I should be using pathlib anyway). 

The real problem is that `powershell Compress-Archive` puts windows path separators in it's zip files, and I'm using that as the build step. Weird.

Actually fixed by 868f38a07b83275a06bdeca5eb9957a5422638d3
